export const APP_NAME = 'onepen'
export const KEY_FOLDER = 'folder-'
export const KEY_FOLDERS = 'folders'
export const KEY_NOTE = 'note-'
export const KEY_SETTINGS = 'settings'
export const KEY_TRASH = 'trash'
